import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Providers from "@/providers";
import { Toaster } from "@/components/ui/sonner";
import Header from "@/components/layout/header";
import { QUERY_KEYS } from "@/constants";
import { getConfigApi } from "@/features/config/api";
import { makeQueryClient } from "@/lib/queryClient";
import { getCurrentUserApi } from "@/features/account/api";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const queryClient = makeQueryClient();

  await queryClient.prefetchQuery({
    queryKey: [QUERY_KEYS.CONFIG],
    queryFn: getConfigApi,
  });

  await queryClient.prefetchQuery({
    queryKey: [QUERY_KEYS.PROFILE],
    queryFn: getCurrentUserApi,
  });

  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        <Providers>
          <div className="min-h-screen flex flex-col">
            <Header />
            <main className="flex-1 flex flex-col justify-center">{children}</main>
          </div>
        </Providers>
        <Toaster position="bottom-right" />
      </body>
    </html>
  );
}
